export const CHANGE_CURRENT_CURRENCY = 'CHANGE_CURRENT_CURRENCY';
export const ADD_FAVOURITE_CURRENCY = 'ADD_FAVOURITE_CURRENCY';
export const REMOVE_FAVOURITE_CURRENCY = 'REMOVE_FAVOURITE_CURRENCY';

